[package]
name = "aoc2024"
edition = "2021"

[dependencies]
anyhow = "1.0"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day1-2"
path = "src/day1-2.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"
